### PR TITLE
Fix allowClear option [Closes #63]

### LINKED ISSUE #63: using `onChange` causes the page to hang
When I try to use the `onChange` binding, the page freezes up until I make my first change on the select. Then the page behaves relatively normally. I think there is some kind of circular checking that happens, when using this handler.  `onSelect` seems to do the trick, not causing hanging.

On a separate note, when trying to test the functionality with enzyme, `simulate('change')` seems to not work, most likely because I'm using `onSelect` instead of `onChange`.

Stack trace:
```
Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at Function.htmlPrefilter
    at jQuery.fn.init.<anonymous>
    at access
    at jQuery.fn.init.html
    at DecoratedClass.Placeholder.createPlaceholder
    at DecoratedClass.createPlaceholder
    at DecoratedClass.Placeholder.update
    at DecoratedClass.update
```

Please let me know if you need more details, thanks.

Addendum:
My `value` is `''`, but my `data` does not contain this value. I think this is what is causing the infinite loop.

### PR DESCRIPTION
**Pull request by jordanbyron**
When the `allowClear` option is enabled and that same component has a `onChange` callback, clicking the clear icon will cause an infinite loop. The root cause seems to be that`this.el.val()` returns `null` when previously set to an empty string, which is what happens when the input is cleared. As expected `shallowEqualFuzzy` returns `false` when comparing `null` to `''` which causes an infinite `onChange` callback loop.

The new `fuzzyValuesEqual` method returns `true` when `currentValue` is `null` and `newValue` is equal to an empty string, otherwise it calls `shallowEqualFuzzy` which was the previous behavior.

I've also updated the examples with a select2 component set to `allowClear` which can be used to manually test the new behavior. Let me know if there is anything you'd like me to change. Thanks! 😄

### CODE REVIEW

File: examples/src/components/Tags.js [hunk 1]
```diff
@@ -287,6 +294,28 @@ export default class Tags extends Component {
     );
   }
 
+  example11() {
+    const { value11, data11, onChange11 } = this.state;
```
Comment (rkit) [inline examples/src/components/Tags.js]: `onChange11` is not defined

Comment (rkit) [inline examples/src/components/Tags.js]: Please fix style issues (eslint)

Comment (jordanbyron) [inline examples/src/components/Tags.js]: All set!

Comment (rkit) [inline examples/src/components/Tags.js]: Thanks!

**Comment by rkit** [comment]
Thanks!
